// DIALOG_BORROWHISTORY.cpp : 实现文件
//

#include "stdafx.h"
#include "DIALOG_BORROWHISTORY.h"



// CDIALOG_BORROWHISTORY 对话框

IMPLEMENT_DYNAMIC(CDIALOG_BORROWHISTORY, CDialog)

CDIALOG_BORROWHISTORY::CDIALOG_BORROWHISTORY(CWnd* pParent /*=NULL*/)
	: CDialog(CDIALOG_BORROWHISTORY::IDD, pParent)
{

}

CDIALOG_BORROWHISTORY::~CDIALOG_BORROWHISTORY()
{
}

void CDIALOG_BORROWHISTORY::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
}


BEGIN_MESSAGE_MAP(CDIALOG_BORROWHISTORY, CDialog)
END_MESSAGE_MAP()


// CDIALOG_BORROWHISTORY 消息处理程序
